[package]
name = "factors"
version = "0.1.0"
edition = "2021"

[dependencies]
factors-methods = { path = "methods" }
risc0-zkvm = { version = "0.16.1" }
serde = "1.0"

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
metal = ["risc0-zkvm/metal"]